services:

  php:
    build: docker/php
    container_name: php
    tty: true
    volumes:
      - ./:/var/www/app
      - ./docker/php/z-overrides.ini:/usr/local/etc/php/conf.d/z-overrides.ini
      - ./supervisor/laravel-sync-worker.conf:/etc/supervisor/conf.d/laravel-sync-worker.conf:ro
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - mysql
    networks:
      - app-network
    env_file:
      .env

  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT:-3308}:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - app-network
    env_file:
      .env

networks:
  app-network:
    driver: bridge